version: '2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3001
    volumes:
      - .:/code
    env_file: .env
    ports:
      - "3001:3001"
  worker:
    build: .
    command: python manage.py rqworker default
    volumes:
      - .:/code
    env_file: .env
  redis:
    image: redis
