# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 13, 18, 5, 18, 115954, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='interface.Repo'),
        ),
    ]
