# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20170413_1105'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([('repo', 'path', 'filename')]),
        ),
    ]
