# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20170413_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='body',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
